// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCma6C5nZZQqClVC1vRecT19YDoOxl9rQ',
    appId: '1:79574877269:web:e8da0ec19ba21735a200dc',
    messagingSenderId: '79574877269',
    projectId: 'my-wife-9f0fb',
    authDomain: 'my-wife-9f0fb.firebaseapp.com',
    storageBucket: 'my-wife-9f0fb.firebasestorage.app',
    measurementId: 'G-K95THZ5FLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1iHNJPDZiRUw2HjWHIEA5PYyDO0ZEgjA',
    appId: '1:79574877269:android:b6934a627b222fc2a200dc',
    messagingSenderId: '79574877269',
    projectId: 'my-wife-9f0fb',
    storageBucket: 'my-wife-9f0fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsHYHLxwAH3hT5AXf45OE0Bi7wrGWfeXI',
    appId: '1:79574877269:ios:6667ded9c7483765a200dc',
    messagingSenderId: '79574877269',
    projectId: 'my-wife-9f0fb',
    storageBucket: 'my-wife-9f0fb.firebasestorage.app',
    iosBundleId: 'com.example.myWife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsHYHLxwAH3hT5AXf45OE0Bi7wrGWfeXI',
    appId: '1:79574877269:ios:6667ded9c7483765a200dc',
    messagingSenderId: '79574877269',
    projectId: 'my-wife-9f0fb',
    storageBucket: 'my-wife-9f0fb.firebasestorage.app',
    iosBundleId: 'com.example.myWife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCma6C5nZZQqClVC1vRecT19YDoOxl9rQ',
    appId: '1:79574877269:web:84fa50f491c33847a200dc',
    messagingSenderId: '79574877269',
    projectId: 'my-wife-9f0fb',
    authDomain: 'my-wife-9f0fb.firebaseapp.com',
    storageBucket: 'my-wife-9f0fb.firebasestorage.app',
    measurementId: 'G-CV9SEN20G8',
  );
}
